version: '3.8'

services:
  rediscachingwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - RedisConnection=redis:6379
      - ConnectionStrings__Employee=Server=sqlserver;Database=Employee;User=sa;Password=YourPassword123!
    ports:
      - "5000:80"  # Override to a different port for development
      - "5001:443" # Override to a different HTTPS port for development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./src:/app  # Ensure your source code changes are reflected immediately during local development

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_TCP_PORT=1433
      - MSSQL_FORCE_ENCRYPTION=0
    ports:
      - "1433:1433"
    volumes:
      - ./RedisCachingWebApi/sql-scripts:/var/opt/mssql/scripts
