version: '3.8'

services:
  rediscachingwebapi:
    build:
      context: ./RedisCachingWebApi
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - redis
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisConnection=redis:6379
      - ConnectionStrings__Employee=Server=sqlserver;Database=Employee;User=sa;Password=YourPassword123!

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_TCP_PORT=1433
      - MSSQL_FORCE_ENCRYPTION=0  # Disable forced encryption
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql  # Persist database data

  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    environment:
      - SA_PASSWORD=YourPassword123!
    volumes:
      - ./RedisCacheDatabase/bin/Debug:/var/opt/mssql/dacpac  # Mount DACPAC folder
    entrypoint: >
      /bin/bash -c "
      echo 'Installing dependencies (libicu and unzip)...';
      apt-get update && apt-get install -y unzip libicu-dev;
      
      curl -L https://aka.ms/sqlpackage-linux -o sqlpackage.zip;
      unzip sqlpackage.zip -d /opt/sqlpackage;
      chmod +x /opt/sqlpackage/sqlpackage;

      echo 'Deploying DACPAC file';
      /opt/sqlpackage/sqlpackage /Action:Publish /SourceFile:/var/opt/mssql/dacpac/RedisCacheDatabase.dacpac \
      /TargetConnectionString:'Server=sqlserver;Initial Catalog=Employee;User Id=sa;Password=YourPassword123!;Encrypt=False;TrustServerCertificate=True' || echo 'Error deploying DACPAC';
      "

volumes:
  sqlserver-data:
