version: '3.8'

services:
  # Web API Service
  webapi:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisConnection=redis:6379

  # Redis Service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
